version: "3"

includes:
  go: 
    taskfile: tasks/golang
    internal: true
  hello-world: 
    taskfile: github.com/campbel/kit/tasks/hello-world
    internal: true

tasks:
  default:
    cmds:
      - task --dir .kit -l
  
  build:
    desc: Build the project
    cmds:
      - task: go:build

  run:
    desc: Run the project
    cmds:
      - task: go:run

  test:
    desc: Run the tests
    cmds:
      - task: go:test