version: "3"

includes:
  go: tasks/golang
  hello-world: 
    taskfile: github.com/campbel/kit/tasks/hello-world
    internal: true

tasks:
  default:
    cmds:
      - task -l
  
  setup:
    desc: Setup the project
    cmds:
      - task: golang:install

  hello-world:
    desc: Run the hello-world project
    cmds:
      - task: hello-world:run