version: "3"

includes:
  golang: github.com/campbel/kit/examples/golang
  hello-world: .task/hello-world

tasks:
  default:
    cmds:
      - task -l
  
  setup:
    desc: Setup the project
    cmds:
      - task: golang:install

  hello-world:
    desc: Run the hello-world project
    cmds:
      - task: hello-world:run