version: "3"

includes:
  golang: 
    taskfile: github.com/campbel/kit/tasks/golang   # Github repo
  hello-world: 
    taskfile: tasks/hello-world                     # Local directory

tasks:
  default:
    cmds:
      - task -l
  
  setup:
    desc: Setup the project
    cmds:
      - task: golang:install

  hello-world:
    desc: Run the hello-world project
    cmds:
      - task: hello-world:run