version: "3"

includes:
  os: taskfile_{{OS}}.yaml

tasks:
  install:
    desc: Install Go
    cmds:
      - task: os:install

  build:
    desc: Go build
    deps: [install]
    vars:
      PKG: '{{default "./..." .PKG}}'
    cmds:
      - go build -o bin/ {{.PKG}}

  run:
    desc: Go run
    deps: [install]
    vars: 
      PKG: '{{default "./..." .PKG}}'
    cmds:
      - go run {{.PKG}}
  
  test:
    desc: Go run
    deps: [install]
    vars: 
      PKG: '{{default "./..." .PKG}}'
      FLAGS: '{{default "-cover" .FLAGS}}'
    cmds:
      - go test {{.PKG}} {{.FLAGS}}