version: "3"

includes:
  os: taskfile_{{OS}}.yaml

tasks:
  install:
    desc: Install Go
    cmds:
      - task: os:install

  build:
    desc: Go build
    cmds:
      - go build -o bin/ ./...

  run:
    desc: Go run
    cmds:
      - go run .